/*
 * This file is generated by jOOQ.
 */
package se.biobanksverige.sbr.db.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.biobanksverige.sbr.db.Keys;
import se.biobanksverige.sbr.db.Public;
import se.biobanksverige.sbr.db.enums.IssueType;
import se.biobanksverige.sbr.db.tables.Issue.IssuePath;
import se.biobanksverige.sbr.db.tables.records.IssueConsentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.2",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssueConsent extends TableImpl<IssueConsentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.issue_consent</code>
     */
    public static final IssueConsent ISSUE_CONSENT = new IssueConsent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IssueConsentRecord> getRecordType() {
        return IssueConsentRecord.class;
    }

    /**
     * The column <code>public.issue_consent.id</code>.
     */
    public final TableField<IssueConsentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.issue_consent.type</code>.
     */
    public final TableField<IssueConsentRecord, IssueType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(IssueType.class), this, "");

    private IssueConsent(Name alias, Table<IssueConsentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IssueConsent(Name alias, Table<IssueConsentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.issue_consent</code> table reference
     */
    public IssueConsent(String alias) {
        this(DSL.name(alias), ISSUE_CONSENT);
    }

    /**
     * Create an aliased <code>public.issue_consent</code> table reference
     */
    public IssueConsent(Name alias) {
        this(alias, ISSUE_CONSENT);
    }

    /**
     * Create a <code>public.issue_consent</code> table reference
     */
    public IssueConsent() {
        this(DSL.name("issue_consent"), null);
    }

    public <O extends Record> IssueConsent(Table<O> path, ForeignKey<O, IssueConsentRecord> childPath, InverseForeignKey<O, IssueConsentRecord> parentPath) {
        super(path, childPath, parentPath, ISSUE_CONSENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IssueConsentPath extends IssueConsent implements Path<IssueConsentRecord> {
        public <O extends Record> IssueConsentPath(Table<O> path, ForeignKey<O, IssueConsentRecord> childPath, InverseForeignKey<O, IssueConsentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IssueConsentPath(Name alias, Table<IssueConsentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IssueConsentPath as(String alias) {
            return new IssueConsentPath(DSL.name(alias), this);
        }

        @Override
        public IssueConsentPath as(Name alias) {
            return new IssueConsentPath(alias, this);
        }

        @Override
        public IssueConsentPath as(Table<?> alias) {
            return new IssueConsentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<IssueConsentRecord> getPrimaryKey() {
        return Keys.ISSUE_CONSENT_PKEY;
    }

    @Override
    public List<ForeignKey<IssueConsentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ISSUE_CONSENT__ISSUE);
    }

    private transient IssuePath _issue;

    /**
     * Get the implicit join path to the <code>public.issue</code> table.
     */
    public IssuePath issue() {
        if (_issue == null)
            _issue = new IssuePath(this, Keys.ISSUE_CONSENT__ISSUE, null);

        return _issue;
    }

    @Override
    public List<Check<IssueConsentRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("type_constraint"), "((type = 'CONSENT'::issue_type))", true)
        );
    }

    @Override
    public IssueConsent as(String alias) {
        return new IssueConsent(DSL.name(alias), this);
    }

    @Override
    public IssueConsent as(Name alias) {
        return new IssueConsent(alias, this);
    }

    @Override
    public IssueConsent as(Table<?> alias) {
        return new IssueConsent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueConsent rename(String name) {
        return new IssueConsent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueConsent rename(Name name) {
        return new IssueConsent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueConsent rename(Table<?> name) {
        return new IssueConsent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IssueConsent where(Condition condition) {
        return new IssueConsent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IssueConsent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IssueConsent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IssueConsent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IssueConsent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IssueConsent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IssueConsent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IssueConsent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IssueConsent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IssueConsent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
