/*
 * This file is generated by jOOQ.
 */
package se.biobanksverige.sbr.db;


import javax.annotation.processing.Generated;

import se.biobanksverige.sbr.db.tables.Issue;
import se.biobanksverige.sbr.db.tables.IssueComplete;
import se.biobanksverige.sbr.db.tables.IssueConsent;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.2",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.issue</code>.
     */
    public static final Issue ISSUE = Issue.ISSUE;

    /**
     * The table <code>public.issue_complete</code>.
     */
    public static final IssueComplete ISSUE_COMPLETE = IssueComplete.ISSUE_COMPLETE;

    /**
     * The table <code>public.issue_consent</code>.
     */
    public static final IssueConsent ISSUE_CONSENT = IssueConsent.ISSUE_CONSENT;
}
