[versions]
flyway = "8.5.13"
jooq = "3.17.5"
junit = "5.8.2"
kotlin = "1.8.0"
plugin-jooq = "8.0"
postgres = "42.2.23"

[libraries]
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
jooq-core = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-kotlin = { module = "org.jooq:jooq-kotlin", version.ref = "jooq" }
jooq-meta-extensions = { module = "org.jooq:jooq-meta-extensions", version.ref = "jooq" }
junit-full = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

[bundles]
jooq = ["jooq-core", "jooq-meta-extensions"]
jooq-kotlin = ["jooq-core", "jooq-kotlin", "jooq-meta-extensions"]

[plugins]
jooq = { id = "nu.studer.jooq", version.ref = "plugin-jooq" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
