/*
 * This file is generated by jOOQ.
 */
package se.strindberg.jooqsimple.db.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;

import se.strindberg.jooqsimple.db.tables.Address;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.2",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends TableRecordImpl<AddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>address.line1</code>.
     */
    public void setLine1(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>address.line1</code>.
     */
    public String getLine1() {
        return (String) get(0);
    }

    /**
     * Setter for <code>address.line2</code>.
     */
    public void setLine2(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>address.line2</code>.
     */
    public String getLine2() {
        return (String) get(1);
    }

    /**
     * Setter for <code>address.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>address.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(String line1, String line2, Long personId) {
        super(Address.ADDRESS);

        setLine1(line1);
        setLine2(line2);
        setPersonId(personId);
        resetChangedOnNotNull();
    }
}
